### ISSUE TITLE
doc_type Parameter

### ISSUE THREAD

**Issue by x0xMaximus** [greedo/python-xbrl#24]
What is the point of including this parameters throughout the project? From what I can tell it's not being used anywhere, and doesn't do anything to further limit parsing of 10K or 10Q document types anyway. Might be worth considering it's removal.

![](http://www.puff.me.uk/ss/HWQuthGZOt3De.png)

**Comment by greedo** [comment]
@x0xMaximus these were part of an older system, I'll definitely take them out.

**Comment by greedo** [comment]
closed with b3f11af4ea09acddd681cce228a72de840078e73 and d6a4c89301eb4056437143914c64295104308de9

**Comment by x0xMaximus** [comment]
@greedo amazing, thanks!
