### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by tomron** [greedo/python-xbrl#25]
marshmallow versions which are equal or greater than 2.0.0 don't support - from marshmallow import Serializer. Therefore need to at least add the version numbers in the relevant places.

**Comment by artemk93** [comment]
Just load the latest update like this:
sudo pip install git+https://github.com/greedo/python-xbrl.git

**Comment by greedo** [comment]
closed with 97fae198b3f79ff83983b1b916eaa0c1b45d9797
