### ISSUE TITLE
ImportError: cannot import name 'Serializer'

### ISSUE THREAD

**Issue by post2web** [greedo/python-xbrl#37]
After importing:
`from xbrl import XBRLParser`
I get error:
<pre>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-c32dc520503c> in <module>()
----> 1 from xbrl import XBRLParser

/usr/local/lib/python3.5/site-packages/xbrl/__init__.py in <module>()
      6 version = (1, 1, 0)
      7 
----> 8 from .xbrl import XBRLParser, GAAP, GAAPSerializer, XBRLParserException

/usr/local/lib/python3.5/site-packages/xbrl/xbrl.py in <module>()
      3 
      4 import re
----> 5 from marshmallow import Serializer, fields
      6 import datetime
      7 import collections

ImportError: cannot import name 'Serializer'
</pre>

**Comment by pwsutherland** [comment]
I am getting the same error.

**Comment by pwsutherland** [comment]
post2web.... greedo addressed the issue
https://github.com/greedo/python-xbrl/issues/21 

you can either get an older veersion of Marshmallow or pull greedo's updates.

Thanks, greedo!

**Comment by greedo** [comment]
Since this will be fixed with a new release to PyPI, I'm closing this @post2web
