### ISSUE TITLE
Incorrect parsing of current_assets and possibly others

### ISSUE THREAD

**Issue by robren** [greedo/python-xbrl#39]
I noticed that in the tests  in many cases the  assert for current_assets was comparing to 0.0 and in other cases was comparing to a value found in the xml file associated with NoncurrentAssets
- The GAAP property name for current assets is us-gaap:AssetsCurrent
- The search regexp in xbrl.py line 206 was searching for currentassets, the wrong properyname also due to the [^s]* in the regexp this was also matching on noncurrentassets, precisely the wrong thing. 
- The tests also appeared to perpetuate this, for example:
  - The test_parse_GAAP10Q_QXInteractive() this was incorrectly checking for an 
     assert result.data['current_assets'] == 46431.0
 -The only tag containing a value of 46431 in the file   "tests/rsh20131231.xml"    is that for Noncurrentassets! 
- A similar issue exists in the current_assets assertion for test_parse_GAAP10K_ThomsonReuters():

I'm  working on  a fix for these  current_asset issues  and just wanted to give a "heads up". I will fix the parsing and the tests.

i recognize that FASB are constantly updating their definitions, I'm using the 2016 recommendations, 

As a follow up I propose we add some assertions in the tests to check that the balance sheer balances e.g that gaap:LiabilitiesAndStockholdersEquity == gaap:Assets

Regards

Rob Rennison

**Comment by greedo** [comment]
Closed with #40
